#!/bin/sh

rm -rf /usr/lib/python3/dist-packages/tm_librarian/__pycache__
rm -rf /usr/lib/python3/dist-packages/tm_librarian/tests/__pycache__

deb-systemd-invoke stop tm-lfs
deb-systemd-invoke disable tm-lfs
deb-systemd-invoke stop tm-librarian
deb-systemd-invoke disable tm-librarian
deb-systemd-invoke stop tm-lmp
deb-systemd-invoke disable tm-lmp
systemctl daemon-reload

#DEBHELPER#
