#!/bin/sh

rm -rf /usr/lib/python3/dist-packages/tm_librarian/__pycache__
rm -rf /usr/lib/python3/dist-packages/tm_librarian/tests/__pycache__
rm -rf /var/hpetm

/bin/systemctl stop tm-lfs
/bin/systemctl disable tm-lfs
/bin/systemctl stop tm-librarian
/bin/systemctl disable tm-librarian
/bin/systemctl stop tm-lmp
/bin/systemctl disable tm-lmp
/bin/systemctl daemon-reload

exit 0
