#!/usr/bin/dh-exec

backend_sqlite3.py		usr/lib/python3/dist-packages/tm_librarian
book_policy.py			usr/lib/python3/dist-packages/tm_librarian
book_register.py		usr/lib/python3/dist-packages/tm_librarian
book_shelf_bos.py		usr/lib/python3/dist-packages/tm_librarian
cmdproto.py			usr/lib/python3/dist-packages/tm_librarian
engine.py			usr/lib/python3/dist-packages/tm_librarian
frdnode.py			usr/lib/python3/dist-packages/tm_librarian
fsck_lfs.py			usr/lib/python3/dist-packages/tm_librarian
genericobj.py			usr/lib/python3/dist-packages/tm_librarian
lfs_fuse.py			usr/lib/python3/dist-packages/tm_librarian
lfs_shadow.py			usr/lib/python3/dist-packages/tm_librarian
librarian.py			usr/lib/python3/dist-packages/tm_librarian
repl_client.py			usr/lib/python3/dist-packages/tm_librarian
socket_handling.py		usr/lib/python3/dist-packages/tm_librarian
sqlassist.py			usr/lib/python3/dist-packages/tm_librarian
sqlbackend.py			usr/lib/python3/dist-packages/tm_librarian
tm_fuse.py			usr/lib/python3/dist-packages/tm_librarian
tm_ioctl_opt.py			usr/lib/python3/dist-packages/tm_librarian
lmp.py				usr/lib/python3/dist-packages/tm_librarian
lmp_config.py			usr/lib/python3/dist-packages/tm_librarian
tmconfig.py			usr/lib/python3/dist-packages/tm_librarian
systemd_tm-lfs			=> etc/default/tm-lfs
systemd_tm-lfs.service		=> lib/systemd/system/tm-lfs.service
systemd_tm-librarian		=> etc/default/tm-librarian
systemd_tm-librarian.service	=> lib/systemd/system/tm-librarian.service
tests/check-book.py		usr/lib/python3/dist-packages/tm_librarian/tests
tests/maptrap.c			usr/lib/python3/dist-packages/tm_librarian/tests
tests/README			usr/lib/python3/dist-packages/tm_librarian/tests
tests/rw_test.py		usr/lib/python3/dist-packages/tm_librarian/tests
tests/test_book_register.py	usr/lib/python3/dist-packages/tm_librarian/tests
tests/test_code_format_pep8.py	usr/lib/python3/dist-packages/tm_librarian/tests
tests/tm-fio-test.fio		usr/lib/python3/dist-packages/tm_librarian/tests
tests/check-ea.py		usr/lib/python3/dist-packages/tm_librarian/tests
templates/show_allocated.html	usr/lib/python3/dist-packages/tm_librarian/templates
templates/show_nodes.html	usr/lib/python3/dist-packages/tm_librarian/templates
templates/show_directory.html	usr/lib/python3/dist-packages/tm_librarian/templates
templates/show_global.html	usr/lib/python3/dist-packages/tm_librarian/templates
templates/show_views.html	usr/lib/python3/dist-packages/tm_librarian/templates
templates/show_active.html	usr/lib/python3/dist-packages/tm_librarian/templates
templates/show_books.html	usr/lib/python3/dist-packages/tm_librarian/templates
templates/show_shelf.html	usr/lib/python3/dist-packages/tm_librarian/templates
templates/show_interleaveGroups.html	usr/lib/python3/dist-packages/tm_librarian/templates
configfiles/book_data.ini	usr/lib/python3/dist-packages/tm_librarian/configfiles
configfiles/book_max.ini	usr/lib/python3/dist-packages/tm_librarian/configfiles
configfiles/fame.json		usr/lib/python3/dist-packages/tm_librarian/configfiles
configfiles/simpleconfig.json	usr/lib/python3/dist-packages/tm_librarian/configfiles
configfiles/tmcf-bristol.json	usr/lib/python3/dist-packages/tm_librarian/configfiles
configfiles/tmcf-drew.json	usr/lib/python3/dist-packages/tm_librarian/configfiles
configfiles/fame_80_node.json	usr/lib/python3/dist-packages/tm_librarian/configfiles
