.TH BOOK_REGISTER.PY 8 2018-03-17 "The Machine" "LFS Management Protocol daemon"

.SH NAME
book_register.py \- Management Protocol Daemon of the Librarian File System (LFS) for The Machine 

.SH SYNOPSIS
\fBbook_register.py\fP [options] [arguments]

.SH DESCRIPTION
\fBbook_register.py\fP is cool

.SH OPTIONS
.PP

.TP
-C, --config
Use the specified file instead of /etc/tmms

.TP
-?
Print a synopsis of all options and hints

.TP
-d
Turn on debugging

.TP
-v
Make it talk

\fP
.SH FILES
Read on.

.PP
.TP
/var/hpetm/librian.db
Default location for the SQLite3 database produced from book_register.py

.SH SEE ALSO
librarian.py
